### PR TITLE
Add units to LATENCY_GAUGE

### PR DESCRIPTION
**Pull request by 2br-2b**

### CODE REVIEW

**Comment by ApolloRoboto** [comment]
Apologies for not getting to this pull request sooner, it's difficult to understand your motives without a description.

Can you explain the reason you need to add this parameter, was there an issue without it?

**Comment by 2br-2b** [comment]
Hey! Not a problem!

There isn't a problem. This works fine; this just adds a units flag to the Prometheus entry.

Thanks for the sample code btw! It's really helped up my bot's monitoring

**Comment by ApolloRoboto** [comment]
All good, I'll be merging this.

The dashboard will need to be updated since this changes the metric name from `discord_latency` to `discord_latency_seconds`. That change will be in 0.2.0

**Comment by ApolloRoboto** [comment]
Version 0.2.0 is up with your changes, make sure to update your dashboards.

Thanks for the contribution!

**Pull request merged**
